import React from "react";
import styles from "./originstory.module.css";

const OriginStory = () => {
  return (
    <div className={styles.StoryMainContainer} id="orign">
      <span className={styles.Heading}>Orign Story</span>
      <div className={styles.description}>
        <span>SHARKYBOY & THE LOST FIN CLAN: ORIGINS</span>
        <p>
          IN THE DARKEST DEPTHS OF THE OCEAN, WHERE SUNLIGHT FADES AND LEGENDS
          ARE BORN, A SECRET EXPERIMENT GAVE RISE TO SOMETHING EXTRAORDINARY-THE
          FIN CLAN. CREATED IN A HIDDEN UNDERWATER LAB, THESE MUTANT SHARK
          WARRIORS WERE ENGINEERED FOR STRENGTH, INTELLIGENCE, AND SURVIVAL. BUT
          WHEN THEIR CREATOR, DR. HEX, TURNED AGAINST THEM, THEIR ONLY CHOICE
          WAS TO FIGHT FOR THEIR FREEDOM.
        </p>
      </div>
      <div className={styles.description}>
        <span>THE BIRTH OF SHARKYBOY</span>
        <p>
          AMONG THEM WAS SHARKYBOY, THE STRONGEST AND MOST RESILIENT OF THE
          CLAN. WITH HIS RED CYBERNETIC EYES, ENHANCED STRENGTH, AND UNMATCHED
          COMBAT SKILLS, HE LED THE CHARGE AGAINST THE SCIENTISTS WHO SOUGHT TO
          CONTROL THEM. THE BATTLE WAS FIERCE, AND THOUGH THE FIN CLAN ESCAPED,
          THEY WERE SEPARATED IN THE CHAOS-SCATTERED ACROSS THE VAST OCEAN, EACH
          FIGHTING TO SURVIVE.
        </p>
      </div>
      <div className={styles.description}>
        <span>THE LOST BROTHERS</span>
        <p>
          NOW, SHARKYBOY SEARCHES FOR HIS LOST BROTHERS-TYPHOON, WAVEBURN, AND
          DRIFT-WHO EACH POSSESS UNIQUE POWERS AND THEIR OWN PIECES OF THE
          PUZZLE THAT WILL ONE DAY REUNITE THE CLAN. BUT LURKING IN THE SHADOWS
          ARE THEIR ENEMIES:
        </p>
        <ul>
          <li>
            LORD ABYSSUS - A DEEP-SEA OVERLORD WHO SEEKS TO CAPTURE THE FIN CLAN
            FOR HIS OWN DARK AGENDA.
          </li>
          <li>
            LEVIATRON - A MONSTROUS BEHEMOTH WHO RULES THE ABYSS WITH BRUTE
            FORCE.
          </li>
          <li>
            BARRICUDA - A RUTHLESS MERCENARY HUNTING THE BROTHERS FOR PROFIT.
          </li>
          <li>
            DR. HEX - THE TWISTED GENIUS WHO CREATED THEM, NOW SEEKING TO
            DESTROY WHAT HE CANNOT CONTROL.
          </li>
          <li>WIDOWWAVE - A MASTER MANIPULATOR WHO THRIVES IN DECEPTION.</li>
        </ul>
      </div>
      <div className={styles.description}>
        <span>THE MISSION</span>
        <p>
          SHARKYBOY'S FIGHT ISN'T JUST FOR SURVIVAL-IT'S FOR REDEMPTION. TO
          REUNITE THE FIN CLAN, DEFEAT THE ENEMIES WHO THREATEN THEIR EXISTENCE,
          AND UNCOVER THE SECRETS BEHIND THEIR CREATION, HE MUST TRAVEL THROUGH
          TREACHEROUS WATERS, UNCOVER HIDDEN TRUTHS, AND RECLAIM THEIR DESTINY.
        </p>
      </div>
      <div className={styles.description}>
        <span>JOIN THE STORY</span>
        <p>
          THE SHARKYBOY NFT GENESIS COLLECTION IS YOUR CHANCE TO BECOME PART OF
          THIS EVOLVING WORLD. HOLDERS OF THESE EXCLUSIVE NFTS WILL SHAPE THE
          FUTURE OF THE SHARKYBOY UNIVERSE-FROM VOTING ON THE NEXT NFT RELEASES
          TO INFLUENCING THE STORYLINE OF FUTURE COMIC BOOKS. THIS IS JUST THE
          BEGINNING. ARE YOU READY TO DIVE IN?
        </p>
      </div>
    </div>
  );
};

export default OriginStory;
